inherit:
  - base.yaml

training:
  task: exp_regression
  batch_size: 64
  num_tasks: 10000
  curriculum:
    points:
      start: 1
      end: 32
      inc: 1
      interval: 200
    dims:
      start: 1
      end: 10
      inc: 1
      interval: 200

out_dir: ../models/exp_regression

wandb:
  project: exp-train
  entity: hzg040122-uc-berkeley-electrical-engineering-computer-sc
  name: "exp-regression"
  notes: "Train and test on y=A*exp(Bx)+C"
  log_every_steps: 10
