inherit:
  - base.yaml

training:
  task: hard_sine2sawtooth
  batch_size: 64
  num_tasks: 10000
  curriculum:
    points:
      start: 1
      end: 32
      inc: 1
      interval: 200
    dims:
      start: 1
      end: 10
      inc: 1
      interval: 200


out_dir: ../models/hard_sine2sawtooth

wandb:
  project: sine-test
  entity: hzg040122-uc-berkeley-electrical-engineering-computer-sc
  name: "hard_sine2sawtooth-run"
  notes: "Training on y=Asin(Bx+C)+D function and testing on sawtooth function."
  log_every_steps: 10