inherit:
  - base.yaml

training:
  task: hard_sine2poly
  batch_size: 64
  num_tasks: 10000
  task_kwargs:
    degree: 3
    scale: 1.0
  curriculum:
    points:
      start: 1
      end: 32
      inc: 1
      interval: 200
    dims:
      start: 1
      end: 10
      inc: 1
      interval: 200

out_dir: ../models/hard_sine2poly

wandb:
  project: sine2poly
  entity: hzg040122-uc-berkeley-electrical-engineering-computer-sc
  name: "hard_sine2poly-run"
  notes: "Train on A*sin(Bx+C)+D, test on polynomial"
  log_every_steps: 10
