inherit:
  - base.yaml

training:
  task: poly_function_regression
  task_kwargs:
    degree: 3
  curriculum:
    points:
      start: 1
      end: 32
      inc: 1
      interval: 1000
    dims:
      start: 1
      end: 10
      inc: 1
      interval: 1000
  batch_size: 64
  learning_rate: 0.0001
  train_steps: 10000

out_dir: ../models/poly_function_regression

wandb:
  project: poly-test
  entity: hzg040122-uc-berkeley-electrical-engineering-computer-sc
  name: "poly-function-run"
  notes: "Training and testing on polynomial functions"
  log_every_steps: 10
