inherit:
  - base.yaml

training:
  task: sine2exp
  batch_size: 64
  num_tasks: 10000
  curriculum:
    points:
      start: 1
      end: 32
      inc: 1
      interval: 200
    dims:
      start: 1
      end: 10
      inc: 1
      interval: 200

out_dir: ../models/sine2exp

wandb:
  project: sine-exp-transfer
  entity: hzg040122-uc-berkeley-electrical-engineering-computer-sc
  name: "sine2exp-run"
  notes: "Train on sine, eval on exp."
  log_every_steps: 10
