inherit:
  - base.yaml

training:
  task: tanh_poly_regression
  batch_size: 64
  num_tasks: 10000
  task_kwargs:
    degree: 3
    scale: 1.0
  curriculum:
    points:
      start: 1
      end: 40
      inc: 1
      interval: 250
    dims:
      start: 1
      end: 40
      inc: 1
      interval: 250

out_dir: ../models/tanh_poly_regression

wandb:
  project: tanh-poly
  entity: hzg040122-uc-berkeley-electrical-engineering-computer-sc
  name: "tanh_poly_run"
  notes: "Train and test on tanh(poly(x))"
  log_every_steps: 10
