inherit:
  - base.yaml

training:
  task: tanh_inverse_regression
  batch_size: 64
  num_tasks: 10000
  curriculum:
    points:
      start: 1
      end: 32
      inc: 1
      interval: 200
    dims:
      start: 1
      end: 10
      inc: 1
      interval: 200


out_dir: ../models/tanh_inverse_regression

wandb:
  project: sine-test
  entity: hzg040122-uc-berkeley-electrical-engineering-computer-sc
  name: "tanh_inverse_regression-run"
  notes: "Training and testing on inverse-tanh(x)"
  log_every_steps: 10